// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: id-generator.proto

package idgenerator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GenerateIdsRequest) Reset() {
	*x = GenerateIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdsRequest) ProtoMessage() {}

func (x *GenerateIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdsRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdsRequest) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIdsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenerateIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GenerateIdsResponse) Reset() {
	*x = GenerateIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdsResponse) ProtoMessage() {}

func (x *GenerateIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdsResponse.ProtoReflect.Descriptor instead.
func (*GenerateIdsResponse) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type TrackIdUsageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsUsed bool   `protobuf:"varint,2,opt,name=isUsed,proto3" json:"isUsed,omitempty"`
}

func (x *TrackIdUsageRequest) Reset() {
	*x = TrackIdUsageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackIdUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackIdUsageRequest) ProtoMessage() {}

func (x *TrackIdUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackIdUsageRequest.ProtoReflect.Descriptor instead.
func (*TrackIdUsageRequest) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{2}
}

func (x *TrackIdUsageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackIdUsageRequest) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

type TrackIdUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackIdUsageResponse) Reset() {
	*x = TrackIdUsageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_id_generator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackIdUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackIdUsageResponse) ProtoMessage() {}

func (x *TrackIdUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_generator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackIdUsageResponse.ProtoReflect.Descriptor instead.
func (*TrackIdUsageResponse) Descriptor() ([]byte, []int) {
	return file_id_generator_proto_rawDescGZIP(), []int{3}
}

var File_id_generator_proto protoreflect.FileDescriptor

var file_id_generator_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x64, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0x2a, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a,
	0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x55, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x55, 0x73, 0x65, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbf, 0x01,
	0x0a, 0x12, 0x49, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x73, 0x12, 0x1f, 0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x49, 0x64, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x64, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x16, 0x5a, 0x14, 0x70, 0x6f, 0x6c, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x69, 0x64, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_id_generator_proto_rawDescOnce sync.Once
	file_id_generator_proto_rawDescData = file_id_generator_proto_rawDesc
)

func file_id_generator_proto_rawDescGZIP() []byte {
	file_id_generator_proto_rawDescOnce.Do(func() {
		file_id_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_id_generator_proto_rawDescData)
	})
	return file_id_generator_proto_rawDescData
}

var file_id_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_id_generator_proto_goTypes = []any{
	(*GenerateIdsRequest)(nil),   // 0: idgenerator.GenerateIdsRequest
	(*GenerateIdsResponse)(nil),  // 1: idgenerator.GenerateIdsResponse
	(*TrackIdUsageRequest)(nil),  // 2: idgenerator.TrackIdUsageRequest
	(*TrackIdUsageResponse)(nil), // 3: idgenerator.TrackIdUsageResponse
}
var file_id_generator_proto_depIdxs = []int32{
	0, // 0: idgenerator.IdGeneratorService.GenerateIds:input_type -> idgenerator.GenerateIdsRequest
	2, // 1: idgenerator.IdGeneratorService.TrackIdUsage:input_type -> idgenerator.TrackIdUsageRequest
	1, // 2: idgenerator.IdGeneratorService.GenerateIds:output_type -> idgenerator.GenerateIdsResponse
	3, // 3: idgenerator.IdGeneratorService.TrackIdUsage:output_type -> idgenerator.TrackIdUsageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_id_generator_proto_init() }
func file_id_generator_proto_init() {
	if File_id_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_id_generator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_generator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_generator_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TrackIdUsageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_id_generator_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TrackIdUsageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_id_generator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_id_generator_proto_goTypes,
		DependencyIndexes: file_id_generator_proto_depIdxs,
		MessageInfos:      file_id_generator_proto_msgTypes,
	}.Build()
	File_id_generator_proto = out.File
	file_id_generator_proto_rawDesc = nil
	file_id_generator_proto_goTypes = nil
	file_id_generator_proto_depIdxs = nil
}
