// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: id-generator.proto

package idgenerator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	IdGeneratorService_GenerateIds_FullMethodName  = "/idgenerator.IdGeneratorService/GenerateIds"
	IdGeneratorService_TrackIdUsage_FullMethodName = "/idgenerator.IdGeneratorService/TrackIdUsage"
)

// IdGeneratorServiceClient is the client API for IdGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdGeneratorServiceClient interface {
	GenerateIds(ctx context.Context, in *GenerateIdsRequest, opts ...grpc.CallOption) (*GenerateIdsResponse, error)
	TrackIdUsage(ctx context.Context, in *TrackIdUsageRequest, opts ...grpc.CallOption) (*TrackIdUsageResponse, error)
}

type idGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGeneratorServiceClient(cc grpc.ClientConnInterface) IdGeneratorServiceClient {
	return &idGeneratorServiceClient{cc}
}

func (c *idGeneratorServiceClient) GenerateIds(ctx context.Context, in *GenerateIdsRequest, opts ...grpc.CallOption) (*GenerateIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdsResponse)
	err := c.cc.Invoke(ctx, IdGeneratorService_GenerateIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idGeneratorServiceClient) TrackIdUsage(ctx context.Context, in *TrackIdUsageRequest, opts ...grpc.CallOption) (*TrackIdUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackIdUsageResponse)
	err := c.cc.Invoke(ctx, IdGeneratorService_TrackIdUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorServiceServer is the server API for IdGeneratorService service.
// All implementations must embed UnimplementedIdGeneratorServiceServer
// for forward compatibility
type IdGeneratorServiceServer interface {
	GenerateIds(context.Context, *GenerateIdsRequest) (*GenerateIdsResponse, error)
	TrackIdUsage(context.Context, *TrackIdUsageRequest) (*TrackIdUsageResponse, error)
	mustEmbedUnimplementedIdGeneratorServiceServer()
}

// UnimplementedIdGeneratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdGeneratorServiceServer struct {
}

func (UnimplementedIdGeneratorServiceServer) GenerateIds(context.Context, *GenerateIdsRequest) (*GenerateIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateIds not implemented")
}
func (UnimplementedIdGeneratorServiceServer) TrackIdUsage(context.Context, *TrackIdUsageRequest) (*TrackIdUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackIdUsage not implemented")
}
func (UnimplementedIdGeneratorServiceServer) mustEmbedUnimplementedIdGeneratorServiceServer() {}

// UnsafeIdGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGeneratorServiceServer will
// result in compilation errors.
type UnsafeIdGeneratorServiceServer interface {
	mustEmbedUnimplementedIdGeneratorServiceServer()
}

func RegisterIdGeneratorServiceServer(s grpc.ServiceRegistrar, srv IdGeneratorServiceServer) {
	s.RegisterService(&IdGeneratorService_ServiceDesc, srv)
}

func _IdGeneratorService_GenerateIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServiceServer).GenerateIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGeneratorService_GenerateIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServiceServer).GenerateIds(ctx, req.(*GenerateIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdGeneratorService_TrackIdUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackIdUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServiceServer).TrackIdUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGeneratorService_TrackIdUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServiceServer).TrackIdUsage(ctx, req.(*TrackIdUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGeneratorService_ServiceDesc is the grpc.ServiceDesc for IdGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idgenerator.IdGeneratorService",
	HandlerType: (*IdGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateIds",
			Handler:    _IdGeneratorService_GenerateIds_Handler,
		},
		{
			MethodName: "TrackIdUsage",
			Handler:    _IdGeneratorService_TrackIdUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "id-generator.proto",
}
